# Generated by Django 5.1.5 on 2025-01-24 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0002_base_menu_user_is_store_owner_user_role_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AddField(
            model_name='menu',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=50),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='fooddelivery.menu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='fooddelivery.store')),
            ],
        ),
    ]
