# Generated by Django 5.1.5 on 2025-01-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0005_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='review',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddelivery.food'),
        ),
    ]
