# Generated by Django 5.1.5 on 2025-01-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0006_remove_review_menu_item_remove_review_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
