# Generated by Django 5.1.5 on 2025-02-01 12:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0007_remove_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
