# Generated by Django 5.1.5 on 2025-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0008_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipped', 'Đã vận chuyển')], default='pending', max_length=50),
        ),
    ]
