# Generated by Django 5.1.5 on 2025-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0010_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipped', 'Đã vận chuyển')], default='pending', max_length=50),
        ),
    ]
