# Generated by Django 5.1.5 on 2025-02-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddelivery', '0014_alter_food_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddelivery.menu'),
        ),
    ]
